-- vim.api.nvim_set_hl(0, 'NavicIconsFile', { default = false, link = 'TSText' })
-- vim.api.nvim_set_hl(0, 'NavicIconsModule', { default = false, link = 'TSText' })
-- vim.api.nvim_set_hl(0, 'NavicIconsNamespace', { default = false, link = 'TSNamespace' })
-- vim.api.nvim_set_hl(0, 'NavicIconsPackage', { default = false, link = 'TSText' })
-- vim.api.nvim_set_hl(0, 'NavicIconsClass', { default = false, link = 'TSType' })
-- vim.api.nvim_set_hl(0, 'NavicIconsMethod', { default = false, link = 'TSMethod' })
-- vim.api.nvim_set_hl(0, 'NavicIconsProperty', { default = false, link = 'TSProperty' })
-- vim.api.nvim_set_hl(0, 'NavicIconsField', { default = false, link = 'TSField' })
-- vim.api.nvim_set_hl(0, 'NavicIconsConstructor', { default = false, link = 'TSConstructor' })
-- vim.api.nvim_set_hl(0, 'NavicIconsEnum', { default = false, link = 'TSType' })
-- vim.api.nvim_set_hl(0, 'NavicIconsInterface', { default = false, link = 'TSType' })
-- vim.api.nvim_set_hl(0, 'NavicIconsFunction', { default = false, link = 'TSFunction' })
-- vim.api.nvim_set_hl(0, 'NavicIconsVariable', { default = false, link = 'TSVariable' })
-- vim.api.nvim_set_hl(0, 'NavicIconsConstant', { default = false, link = 'TSConstant' })
-- vim.api.nvim_set_hl(0, 'NavicIconsString', { default = false, link = 'TSString' })
-- vim.api.nvim_set_hl(0, 'NavicIconsNumber', { default = false, link = 'TSNumber' })
-- vim.api.nvim_set_hl(0, 'NavicIconsBoolean', { default = false, link = 'TSBoolean' })
-- vim.api.nvim_set_hl(0, 'NavicIconsArray', { default = false, link = 'TSType' })
-- vim.api.nvim_set_hl(0, 'NavicIconsObject', { default = false, link = 'TSType' })
-- vim.api.nvim_set_hl(0, 'NavicIconsKey', { default = false, link = 'TSType' })
-- vim.api.nvim_set_hl(0, 'NavicIconsNull', { default = false, link = 'TSText' })
-- vim.api.nvim_set_hl(0, 'NavicIconsEnumMember', { default = false, link = 'TSText' })
-- vim.api.nvim_set_hl(0, 'NavicIconsStruct', { default = false, link = 'TSType' })
-- vim.api.nvim_set_hl(0, 'NavicIconsEvent', { default = false, link = 'TSText' })
-- vim.api.nvim_set_hl(0, 'NavicIconsOperator', { default = false, link = 'TSOperator' })
-- vim.api.nvim_set_hl(0, 'NavicIconsTypeParameter', { default = false, link = 'TSParameter' })
-- vim.api.nvim_set_hl(0, 'NavicText', { default = false, link = 'TSText' })
-- vim.api.nvim_set_hl(0, 'NavicSeparator', { default = false, link = 'TSType' })

vim.api.nvim_set_hl(0, 'NvimTreeNormal', { link = 'Normal' })
-- vim.api.nvim_set_hl(0, "NvimTreeEndOfBuffer", { link = "None" })
-- vim.api.nvim_set_hl(0, "TelescopeSelection", { link = "Visual" })
vim.api.nvim_set_hl(0, 'EndOfBuffer', { link = 'None' })
vim.api.nvim_set_hl(0, 'StatusLine', { link = 'Normal' })
-- vim.api.nvim_set_hl(0, "StatusLineNC", { link = "Normal" })

-- vim.api.nvim_set_hl(0, 'NoiceFormatProgressDone', { default = false, link = 'Pmenu' })
-- vim.api.nvim_set_hl(0, 'NoiceFormatProgressTodo', { default = false, link = 'Pmenu' })
-- vim.api.nvim_set_hl(0, 'NoiceFormatTitle', { default = false, link = 'NvimTreeFolderIcon' })
-- vim.api.nvim_set_hl(0, 'NoiceLspProgressClient', { default = false, link = 'NvimTreeFolderIcon' })
-- vim.api.nvim_set_hl(0, 'NoiceLspProgressSpinner', { default = false, link = 'NvimTreeFolderIcon' })
-- vim.api.nvim_set_hl(0, 'NoiceLspProgressTitle', { default = false, link = 'NvimTreeFolderIcon' })
